x-service-templates:
  payment-processor: &payment-processor
    image: zanfranceschi/payment-processor:amd64-20250707101540
    networks:
      - payment-processor
      - payment-processor-db
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"
  
  payment-processor-db: &payment-processor-db
    image: postgres:17-alpine
    networks:
      - payment-processor-db
    volumes:
      - ./init-processor.sql:/docker-entrypoint-initdb.d/init-processor.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

services:
  payment-processor-1:
    <<: *payment-processor
    container_name: payment-processor-default
    hostname: payment-processor-default
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-default-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8001:8080
    depends_on:
      - payment-processor-db-1
    
  payment-processor-db-1:
    <<: *payment-processor-db
    container_name: payment-processor-default-db
    hostname: payment-processor-default-db

  payment-processor-2:
    <<: *payment-processor
    container_name: payment-processor-fallback
    hostname: payment-processor-fallback
    environment:
      - TRANSACTION_FEE=0.15
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-fallback-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8002:8080
    networks:
      - payment-processor
      - payment-processor-db
    depends_on:
      - payment-processor-db-2
  
  payment-processor-db-2:
    <<: *payment-processor-db
    container_name: payment-processor-fallback-db
    hostname: payment-processor-fallback-db

##### Minha infra
  postgres:
    image: postgres:16
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-router.sql:/docker-entrypoint-initdb.d/init-router.sql
    networks:
      - payment-router
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  api01: &api
    image: quarkus-payment-router:test
    container_name: api1
    hostname: api01
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      THREAD_POOL: 20
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/payment_db
      QUARKUS_REST_CLIENT_DEFAULT_API_URL: http://payment-processor-default:8080
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "70MB"
    networks:
      - payment-router
      - payment-processor
  api02:
    <<: *api
    hostname: api02
    container_name: api2
    ports:
      - "8082:8080"

  load_balancer:
    image: suntzu12/lua-load-balancer:1.0.0
    container_name: load_balancer
    depends_on:
      - api01
      - api02
      - redis
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
    networks:
      - payment-router

  worker:
    image: suntzu12/go-worker:1.0.0
    container_name: worker
    depends_on:
      - redis
    networks:
      - payment-router
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - payment-router
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
  payment-processor-db:
    driver: bridge
  payment-router:
    driver: bridge