name: Create And Push Image to Docker Hub

on:
  push:
    tags: ['*']

jobs:
  create-image:
    name: CREATE IMAGE
    runs-on: self-hosted
    environment: development
    concurrency: development
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Create Image With Docker
        run: |
          echo "Get New Tag Version"
          last_tag=$(git tag -l *.*.* | sort -V | tail -n 1)
          echo "Creating Container with version: $last_tag"
          docker build -t suntzu12/quarkus-payment-router:$last_tag -f docker/Dockerfile.native-micro .    

  push-image:
    needs: create-image
    name: PUSH IMAGE TO DOCKERHUB
    runs-on: self-hosted
    environment: development
    concurrency: development
    steps:
      - name: Login on Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Pushing Image to Dockerhub
        run: |
          last_tag=$(git tag -l *.*.* | sort -V | tail -n 1)
          docker tag suntzu12/quarkus-payment-router:$last_tag suntzu12/quarkus-payment-router:$last_tag
          docker push suntzu12/quarkus-payment-router:$last_tag